name: Generate SVG images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Generate SVG images
        run: npm run generate-svg
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.3.1
        with:
          commit_message: 'Generate SVG images'
          commit_options: '--no-verify'
